USE [NaRegua_Api]

CREATE TABLE USERS
(
	NAME VARCHAR(255),
	DOCUMENT VARCHAR(20) PRIMARY KEY,
	EMAIL VARCHAR(100),
	PHONE VARCHAR(20),
	USERNAME VARCHAR(100),
	PASSWORD VARCHAR(255),
	ISCUSTOMER BIT
)

CREATE TABLE SCHEDULING_USERS
(
	USER_DOCUMENT VARCHAR(20),
	PROFESSIONAL_NAME VARCHAR(255),
	PROFESSIONAL_PHONE VARCHAR(20),
	SALOON_ADRESS VARCHAR(100),
	DATETIME DATETIME
)

CREATE TABLE SALOONS
(
	CODE VARCHAR(50) PRIMARY KEY,
	ADDRESS VARCHAR(255),
	NAME VARCHAR(100),
	CONTACT VARCHAR(20)
)

CREATE TABLE AVAILABILITY_PROFESSIONALS
(
	PROFESSIONAL_DOCUMENT VARCHAR(20),
	DATETIME DATETIME
)

CREATE TABLE SCHEDULING_PROFESSIONALS
(
	PROFESSIONAL_DOCUMENT VARCHAR(20),
	CLIENT_NAME VARCHAR(255),
	CLIENT_PHONE VARCHAR(20),
	DATETIME DATETIME
)

CREATE TABLE EVALUATION_AVERAGES_PROFESSIONALS
(
	PROFESSIONAL_DOCUMENT VARCHAR(20),
	EVALUATION FLOAT
)

CREATE TABLE USERS_FAVORITE_SALONS
(
	USER_DOCUMENT VARCHAR(20),
	SALOON_CODE VARCHAR(50) PRIMARY KEY,
)

insert into USERS_FAVORITE_SALONS values ('151514','978C50')
SELECT * FROM USERS_FAVORITE_SALONS

SELECT * FROM SALOONS

SELECT * FROM USERS

SELECT DISTINCT * FROM SCHEDULING_USERS

insert into SCHEDULING_USERS
values ('151514','xxxx','xxxxx','xxxxx', GETDATE() + 10)

